name: Test reusable workflow
on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    uses: ./.github/workflows/setup-test.yml
    strategy:
      matrix:
        target: ["one", "two"]
    with:
      matrix-step-name: setup
      matrix-key: ${{ matrix.target }}
      in: ${{ matrix.target }}

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./
        id: current
        with:
          matrix-step-name: setup

    outputs:
      result: "${{ steps.current.outputs.result }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: nick-fields/assert-action@0efd6166067d9c59d89c710fab4f79fb066f8985 # v4.0.1
        with:
          expected: 'one'
          actual: ${{ fromJson(needs.test.outputs.result).result.one }}

      - uses: nick-fields/assert-action@0efd6166067d9c59d89c710fab4f79fb066f8985 # v4.0.1
        with:
          expected: 'two'
          actual: ${{ fromJson(needs.test.outputs.result).result.two }}

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Tear down
        run: echo "Do Tear down"
